import { Client, Message, Memory, Insight, DealStats } from '@/types';

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    company: 'ABC Corp',
    email: 'sarah.chen@abccorp.com',
    phone: '+1 (555) 123-4567',
    dealValue: 75000,
    stage: 'negotiation',
    status: 'hot',
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-04-12T14:30:00Z',
  },
  {
    id: '2',
    name: 'Michael Torres',
    company: 'XYZ Ltd',
    email: 'm.torres@xyzltd.com',
    phone: '+1 (555) 234-5678',
    dealValue: 45000,
    stage: 'proposal',
    status: 'warm',
    createdAt: '2026-03-20T09:00:00Z',
    updatedAt: '2026-04-10T11:00:00Z',
  },
  {
    id: '3',
    name: 'Emily Watson',
    company: 'Nova Inc',
    email: 'emily.w@novainc.io',
    phone: '+1 (555) 345-6789',
    dealValue: 120000,
    stage: 'closed',
    status: 'warm',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-04-05T16:00:00Z',
  },
  {
    id: '4',
    name: 'David Kim',
    company: 'TechStart',
    email: 'david.kim@techstart.io',
    phone: '+1 (555) 456-7890',
    dealValue: 35000,
    stage: 'lead',
    status: 'cold',
    createdAt: '2026-04-11T14:00:00Z',
    updatedAt: '2026-04-11T14:00:00Z',
  },
  {
    id: '5',
    name: 'Jessica Martinez',
    company: 'GlobalTech',
    email: 'j.martinez@globaltech.com',
    phone: '+1 (555) 567-8901',
    dealValue: 95000,
    stage: 'negotiation',
    status: 'hot',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-04-12T09:00:00Z',
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    clientId: '1',
    content: 'The price is too high for our budget right now.',
    sender: 'client',
    timestamp: '2026-04-10T10:00:00Z',
  },
  {
    id: '2',
    clientId: '1',
    content: 'I understand your concern. Let me explain the value proposition...',
    sender: 'user',
    timestamp: '2026-04-10T10:05:00Z',
  },
  {
    id: '3',
    clientId: '1',
    content: 'We need to get approval from our CFO, which takes about 2 weeks.',
    sender: 'client',
    timestamp: '2026-04-11T14:00:00Z',
  },
  {
    id: '4',
    clientId: '1',
    content: 'Based on past interactions, this client is budget-sensitive. I recommend offering a tiered pricing option and highlighting ROI within 6 months.',
    sender: 'ai',
    timestamp: '2026-04-11T14:05:00Z',
    memory: {
      retrieved: true,
      pastObjections: ['price too high (2x)', 'needs approval'],
      behaviorPatterns: ['slow decision maker', 'budget conscious'],
      winningStrategies: ['tiered pricing', 'ROI highlight'],
      failedAttempts: ['generic discount offer'],
    },
  },
  {
    id: '5',
    clientId: '1',
    content: 'Can we schedule a call with your technical team?',
    sender: 'client',
    timestamp: '2026-04-12T09:00:00Z',
  },
  {
    id: '6',
    clientId: '1',
    content: 'Absolutely! I can set up a demo with our solutions engineer. Given your technical requirements, I recommend a 45-minute session to cover integration specifics.',
    sender: 'ai',
    timestamp: '2026-04-12T09:02:00Z',
    memory: {
      retrieved: true,
      pastObjections: ['price too high (2x)', 'needs approval', 'technical questions'],
      behaviorPatterns: ['slow decision maker', 'budget conscious', 'analytical'],
      winningStrategies: ['tiered pricing', 'ROI highlight', 'technical demo'],
      failedAttempts: ['generic discount offer'],
    },
  },
];

export const mockMemories: Memory[] = [
  {
    id: '1',
    clientId: '1',
    type: 'objection',
    content: 'Price is too high',
    tags: ['objection:price', 'priority:high'],
    metadata: { frequency: 2, resolved: false },
    timestamp: '2026-04-10T10:00:00Z',
  },
  {
    id: '2',
    clientId: '1',
    type: 'objection',
    content: 'Needs approval from CFO',
    tags: ['objection:approval', 'priority:medium'],
    metadata: { frequency: 1, resolved: false },
    timestamp: '2026-04-11T14:00:00Z',
  },
  {
    id: '3',
    clientId: '1',
    type: 'strategy',
    content: 'Offer tiered pricing to address budget concerns',
    tags: ['strategy:tiered-pricing', 'success_rate:high'],
    metadata: { suggested: true, applied: false },
    timestamp: '2026-04-11T14:05:00Z',
  },
  {
    id: '4',
    clientId: '1',
    type: 'behavior',
    content: 'Slow decision maker - needs comprehensive info',
    tags: ['behavior:slow-decision', 'type:analytical'],
    metadata: { confidence: 0.85 },
    timestamp: '2026-04-12T09:00:00Z',
  },
  {
    id: '5',
    clientId: '2',
    type: 'objection',
    content: 'Currently using competitor product',
    tags: ['objection:competitor', 'priority:high'],
    metadata: { competitor: 'CompetitorX', frequency: 1 },
    timestamp: '2026-04-08T10:00:00Z',
  },
  {
    id: '6',
    clientId: '2',
    type: 'success',
    content: 'Successfully closed with 15% discount + premium support',
    tags: ['strategy:discount', 'success'],
    metadata: { discount: 15, addons: ['premium-support'] },
    timestamp: '2026-04-05T16:00:00Z',
  },
];

export const mockInsights: Insight[] = [
  {
    id: '1',
    type: 'objection_trend',
    title: 'Price Objection Surge',
    description: '45% of active deals have price-related objections this month.',
    suggestion: 'Consider adding a budget-friendly tier to your pricing page.',
    confidence: 0.92,
    timestamp: '2026-04-12T08:00:00Z',
  },
  {
    id: '2',
    type: 'success_pattern',
    title: 'Follow-up Timing',
    description: 'Deals with follow-up within 24 hours have 60% higher close rate.',
    suggestion: 'Prioritize quick follow-ups for new leads.',
    confidence: 0.88,
    timestamp: '2026-04-12T08:00:00Z',
  },
  {
    id: '3',
    type: 'strategy_suggestion',
    title: 'ABC Corp Strategy',
    description: 'Client has mentioned price 2x. Past successful response: tiered pricing.',
    suggestion: 'Offer flexible payment terms and highlight 6-month ROI.',
    confidence: 0.82,
    timestamp: '2026-04-12T09:00:00Z',
  },
  {
    id: '4',
    type: 'risk_alert',
    title: 'Stalled Deal Risk',
    description: 'XYZ Ltd has been in proposal stage for 14 days without update.',
    suggestion: 'Send personalized follow-up mentioning case studies.',
    confidence: 0.75,
    timestamp: '2026-04-12T07:00:00Z',
  },
];

export const mockStats: DealStats = {
  totalDeals: 24,
  activeDeals: 8,
  winRate: 62,
  suggestionsToday: 14,
  avgDealSize: 65000,
  objectionRate: 45,
};

export const mockStageData = [
  { name: 'Lead', value: 6, color: '#6366F1' },
  { name: 'Contacted', value: 4, color: '#8B5CF6' },
  { name: 'Negotiation', value: 3, color: '#A855F7' },
  { name: 'Proposal', value: 2, color: '#EC4899' },
  { name: 'Closed', value: 9, color: '#22C55E' },
];

export const mockObjectionData = [
  { name: 'Price', value: 45, color: '#F59E0B' },
  { name: 'Competitor', value: 35, color: '#6366F1' },
  { name: 'Trust', value: 20, color: '#22C55E' },
];

export const mockWeeklyData = [
  { day: 'Mon', deals: 3, objections: 2 },
  { day: 'Tue', deals: 5, objections: 3 },
  { day: 'Wed', deals: 4, objections: 1 },
  { day: 'Thu', deals: 6, objections: 4 },
  { day: 'Fri', deals: 4, objections: 2 },
  { day: 'Sat', deals: 1, objections: 0 },
  { day: 'Sun', deals: 1, objections: 1 },
];